# Generated by Django 2.1.7 on 2019-02-22 23:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaicsCodesData',
            fields=[
                ('codes', models.IntegerField(primary_key=True, serialize=False)),
                ('titles', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'naics_codes_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OshaInspectionData',
            fields=[
                ('activity_nr', models.IntegerField(primary_key=True, serialize=False)),
                ('reporting_id', models.IntegerField(blank=True, null=True)),
                ('state_flag', models.CharField(blank=True, max_length=6, null=True)),
                ('estab_name', models.CharField(blank=True, max_length=128, null=True)),
                ('site_address', models.CharField(blank=True, max_length=200, null=True)),
                ('site_city', models.CharField(blank=True, max_length=64, null=True)),
                ('site_state', models.CharField(blank=True, max_length=2, null=True)),
                ('site_zip', models.IntegerField(blank=True, null=True)),
                ('owner_type', models.CharField(blank=True, max_length=32, null=True)),
                ('owner_code', models.IntegerField(blank=True, null=True)),
                ('adv_notice', models.CharField(blank=True, max_length=2, null=True)),
                ('safety_hlth', models.CharField(blank=True, max_length=2, null=True)),
                ('sic_code', models.IntegerField(blank=True, null=True)),
                ('naics_code', models.IntegerField(blank=True, null=True)),
                ('insp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('insp_scope', models.CharField(blank=True, max_length=20, null=True)),
                ('why_no_insp', models.CharField(blank=True, max_length=32, null=True)),
                ('union_status', models.CharField(blank=True, max_length=6, null=True)),
                ('safety_manuf', models.CharField(blank=True, max_length=10, null=True)),
                ('safety_const', models.CharField(blank=True, max_length=10, null=True)),
                ('safety_marit', models.CharField(blank=True, max_length=10, null=True)),
                ('health_manuf', models.CharField(blank=True, max_length=10, null=True)),
                ('health_const', models.CharField(blank=True, max_length=10, null=True)),
                ('health_marit', models.CharField(blank=True, max_length=10, null=True)),
                ('migrant', models.CharField(blank=True, max_length=10, null=True)),
                ('mail_street', models.CharField(blank=True, max_length=200, null=True)),
                ('mail_city', models.CharField(blank=True, max_length=64, null=True)),
                ('mail_state', models.CharField(blank=True, max_length=2, null=True)),
                ('mail_zip', models.IntegerField(blank=True, null=True)),
                ('host_est_key', models.CharField(blank=True, max_length=20, null=True)),
                ('nr_in_estab', models.IntegerField(blank=True, null=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('case_mod_date', models.DateField(blank=True, null=True)),
                ('close_conf_date', models.DateField(blank=True, null=True)),
                ('close_case_date', models.DateField(blank=True, null=True)),
                ('ld_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'osha_inspection_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OshaSevereInjuryData',
            fields=[
                ('injury_index', models.IntegerField(primary_key=True, serialize=False)),
                ('incident_id', models.BigIntegerField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('employer', models.CharField(blank=True, max_length=128, null=True)),
                ('address1', models.CharField(blank=True, max_length=128, null=True)),
                ('address2', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('naics_code', models.IntegerField(blank=True, null=True)),
                ('hospitalized', models.SmallIntegerField(blank=True, null=True)),
                ('amputation', models.SmallIntegerField(blank=True, null=True)),
                ('final_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('body_part', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'osha_severe_injury_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SicCodesData',
            fields=[
                ('code', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'sic_codes_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsStatesSpatialData',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('statefp', models.CharField(blank=True, max_length=2, null=True)),
                ('statens', models.CharField(blank=True, max_length=8, null=True)),
                ('affgeoid', models.CharField(blank=True, max_length=11, null=True)),
                ('geoid', models.CharField(blank=True, max_length=2, null=True)),
                ('stusps', models.CharField(blank=True, max_length=2, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lsad', models.CharField(blank=True, max_length=2, null=True)),
                ('aland', models.FloatField(blank=True, null=True)),
                ('awater', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'us_states_spatial_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZipcodesSpatialData',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('descriptio', models.CharField(blank=True, max_length=254, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=24, null=True)),
                ('begin', models.CharField(blank=True, max_length=24, null=True)),
                ('end', models.CharField(blank=True, max_length=24, null=True)),
                ('altitudemo', models.CharField(blank=True, max_length=254, null=True)),
                ('tessellate', models.BigIntegerField(blank=True, null=True)),
                ('extrude', models.BigIntegerField(blank=True, null=True)),
                ('visibility', models.BigIntegerField(blank=True, null=True)),
                ('draworder', models.BigIntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=254, null=True)),
                ('zcta5ce10', models.CharField(blank=True, max_length=254, null=True)),
                ('affgeoid10', models.CharField(blank=True, max_length=254, null=True)),
                ('geoid10', models.CharField(blank=True, max_length=254, null=True)),
                ('aland10', models.CharField(blank=True, max_length=254, null=True)),
                ('awater10', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=4, null=True, srid=4326)),
            ],
            options={
                'db_table': 'zipcodes_spatial_data',
                'managed': False,
            },
        ),
    ]
