# Generated by Django 2.1.7 on 2019-03-05 03:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatalitiesDataTable',
            fields=[
                ('fid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fatalities_data_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FatalitiesStatesCount',
            fields=[
                ('year_s', models.FloatField(blank=True, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fatalities_states_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InjuryStateCount',
            fields=[
                ('year_s', models.FloatField(blank=True, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'injury_state_count',
                'managed': False,
            },
        ),
    ]
