# Generated by Django 2.1.7 on 2019-03-16 18:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization_map', '0002_fatalitiesdatatable_fatalitiesstatescount_injurystatecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatalitiesStatesAllYears',
            fields=[
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fatalities_states_all_years',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FatalitiesStatesCountYear',
            fields=[
                ('year_s', models.FloatField(blank=True, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fatalities_states_count_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionStateAll',
            fields=[
                ('site_state', models.CharField(blank=True, max_length=2, null=True)),
                ('site_zip', models.IntegerField(blank=True, null=True)),
                ('owner_type', models.CharField(blank=True, max_length=32, null=True)),
                ('adv_notice', models.CharField(blank=True, max_length=2, null=True)),
                ('safety_hlth', models.CharField(blank=True, max_length=2, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('titles', models.CharField(blank=True, max_length=300, null=True)),
                ('insp_scope', models.CharField(blank=True, max_length=20, null=True)),
                ('why_no_insp', models.CharField(blank=True, max_length=32, null=True)),
                ('union_status', models.CharField(blank=True, max_length=6, null=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_case_date', models.DateField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inspection_state_all',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SevereInjuryData',
            fields=[
                ('event_date', models.DateField(blank=True, null=True)),
                ('employer', models.CharField(blank=True, max_length=128, null=True)),
                ('address1', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=300, null=True)),
                ('hospitalized', models.SmallIntegerField(blank=True, null=True)),
                ('amputation', models.SmallIntegerField(blank=True, null=True)),
                ('final_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('body_part', models.CharField(blank=True, max_length=64, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'severe_injury_data',
                'managed': False,
            },
        ),
    ]
