# Generated by Django 2.1.7 on 2019-03-17 04:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization_map', '0003_fatalitiesstatesallyears_fatalitiesstatescountyear_inspectionstateall_severeinjurydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInspections17',
            fields=[
                ('estab_name', models.CharField(blank=True, max_length=128, null=True)),
                ('site_city', models.CharField(blank=True, max_length=64, null=True)),
                ('site_state', models.CharField(blank=True, max_length=2, null=True)),
                ('site_zip', models.IntegerField(blank=True, null=True)),
                ('owner_type', models.CharField(blank=True, max_length=32, null=True)),
                ('adv_notice', models.CharField(blank=True, max_length=2, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('titles', models.CharField(blank=True, max_length=300, null=True)),
                ('insp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('insp_scope', models.CharField(blank=True, max_length=20, null=True)),
                ('union_status', models.CharField(blank=True, max_length=6, null=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'all_inspections_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FatalitiesFy1617',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('stusps', models.CharField(blank=True, max_length=2, null=True)),
                ('fatalities', models.BigIntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fatalities_fy_16_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoInspections17',
            fields=[
                ('estab_name', models.CharField(blank=True, max_length=128, null=True)),
                ('site_city', models.CharField(blank=True, max_length=64, null=True)),
                ('site_state', models.CharField(blank=True, max_length=2, null=True)),
                ('site_zip', models.IntegerField(blank=True, null=True)),
                ('owner_type', models.CharField(blank=True, max_length=32, null=True)),
                ('adv_notice', models.CharField(blank=True, max_length=2, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('titles', models.CharField(blank=True, max_length=300, null=True)),
                ('insp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('insp_scope', models.CharField(blank=True, max_length=20, null=True)),
                ('union_status', models.CharField(blank=True, max_length=6, null=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'no_inspections_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SevereInjury2017',
            fields=[
                ('event_date', models.DateField(blank=True, null=True)),
                ('employer', models.CharField(blank=True, max_length=128, null=True)),
                ('address1', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=300, null=True)),
                ('hospitalized', models.SmallIntegerField(blank=True, null=True)),
                ('amputation', models.SmallIntegerField(blank=True, null=True)),
                ('final_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('body_part', models.CharField(blank=True, max_length=64, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'severe_injury_2017',
                'managed': False,
            },
        ),
    ]
