# Generated by Django 2.1.7 on 2019-03-17 19:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization_map', '0004_allinspections17_fatalitiesfy1617_noinspections17_severeinjury2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident17',
            fields=[
                ('insp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('stusps', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'accident_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complaint17',
            fields=[
                ('insp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('stusps', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'complaint_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FatCat17',
            fields=[
                ('insp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('stusps', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fat_cat_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Followup17',
            fields=[
                ('insp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('stusps', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'followup_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monitoring17',
            fields=[
                ('insp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('stusps', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'monitoring_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planned17',
            fields=[
                ('insp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('stusps', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'planned_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referrals17',
            fields=[
                ('insp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('stusps', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'referrals_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variance17',
            fields=[
                ('insp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('stusps', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'variance_17',
                'managed': False,
            },
        ),
    ]
