# Generated by Django 2.1.7 on 2019-03-28 21:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization_map', '0005_accident17_complaint17_fatcat17_followup17_monitoring17_planned17_referrals17_variance17'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmputationCountGraph',
            fields=[
                ('event_month', models.TextField(blank=True, null=True)),
                ('injury_count', models.BigIntegerField(blank=True, null=True)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'amputation_count_graph',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FatalitiesCountGraph',
            fields=[
                ('event_month', models.TextField(blank=True, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fatalities_count_graph',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalizedCountGraph',
            fields=[
                ('event_month', models.TextField(blank=True, null=True)),
                ('injury_count', models.BigIntegerField(blank=True, null=True)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hospitalized_count_graph',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referral17',
            fields=[
                ('insp_type', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'referral_17',
                'managed': False,
            },
        ),
    ]
