# Generated by Django 2.1.7 on 2019-03-29 18:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization_map', '0006_amputationcountgraph_fatalitiescountgraph_hospitalizedcountgraph_referral17'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatalitiesStates17',
            fields=[
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('fatalities', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fatalities_states_17',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FatalitiesZipMap',
            fields=[
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('injury_count', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=4, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fatalities_zip_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SevereInjuryMap',
            fields=[
                ('code', models.CharField(blank=True, max_length=2, null=True)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fatalities', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'severe_injury_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SevereInjuryZipMap',
            fields=[
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('injury_count', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=4, null=True, srid=4326)),
                ('fid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'severe_injury_zip_map',
                'managed': False,
            },
        ),
    ]
